MODULE util

IMPLICIT NONE
!parameters
INTEGER, PARAMETER      :: in1 = SELECTED_INT_KIND(1)
INTEGER, PARAMETER      :: in4 = SELECTED_INT_KIND(6)     
INTEGER, PARAMETER      :: re8 = SELECTED_REAL_KIND(15, 307)
CONTAINS

END MODULE util
